[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["npm --version", "node --version"]

[phases.build]
cmds = [
    "chmod +x build.sh",
    "./build.sh"
]

[start]
cmd = "python web_server.py"