[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["npm --version", "node --version"]

[phases.build]
cmds = [
    "cd frontend && npm install",
    "cd frontend && npm run build",
    "ls -la static/dist/ || echo 'No dist folder'"
]

[start]
cmd = "python web_server.py"