[phases.setup]
nixPkgs = ["nodejs_18", "python311", "gcc"]

[phases.install]
cmds = [
    "npm --version", 
    "node --version",
    "python --version",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "chmod +x build.sh",
    "./build.sh"
]

[start]
cmd = "python web_server.py"